// <auto-generated />
namespace Obligatorisk1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedRequiredFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedRequiredFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201511161328543_addedRequiredFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
